// Operative checklist templates per campaign (ported verbatim from the codebase).
window.CHECKLIST_TEMPLATES = {
  "bienvenida": [
    { "title": "Planificación de campaña call y definición speech y objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Revisión Journey Campaña Bienvenida", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Definición de comunicaciones y canales", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Definición de fechas con equipo matrícula y comercial", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Elaboración de piezas de campaña", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Evaluación de resultados", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Planificación de charlas con DCs", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Planificación de charlas de bienvenida", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Charlas con DC", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío de comunicaciones (SMS, Mail Pers, Portal)", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Planificación de charlas de bienvenida con Producto Virtual", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Elaboración de piezas para Charlas", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Envío de comunicaciones Charlas (SMS, Mail Pers, Portal)", "owner": "Canales y Atención", "month": "Mayo" }
  ],
  "reinscritos": [
    { "title": "Evaluación de resultados", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Envío de comunicaciones (SMS, Mail Pers, Portal)", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Revisión Journey Campaña Reinscritos", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Definición de canales de comunicación", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Preparación de curva de pagos y matrículas", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Eliminicación de tricas y sanciones al ciclo cerrado", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Visualización de cursos disponibles para oferta", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Elaboración de estrategia y propuesta de valor campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Preparación y activación de reportes campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Revisión de reportes campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Elaboración de speech y piezas de comunicación campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Dimensionamiento Call campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Envío de comunicaciones campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Gestión call out campaña no matriculados con deuda", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío comunicado de matrícula", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío turno mañana", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío hoy es tu turno", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío recordatorio de turno", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío de se extendió la matrícula", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío matrícula extemporánea", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío matrícula extendida", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Elaboración de base de campaña (pre matrícula)", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Elaboración de material (video,tenores,  piezas, geniallys, etc)", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Envío comunicación Pago de matrícula", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Activación de botón  turno y horarios", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Activación de panel BI", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío matricúlate hoy (No se matricularon)", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Envío de turnos de matrícula (Previo)", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Analisis de Deserción", "owner": "Canales y Atención", "month": "" }
  ],
  "reincorporados": [
    { "title": "Activación de reportes BI", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Capacitación Call previo inicio campaña", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Planificación de campaña call y definición speech y objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Definición de comunicaciones y canales", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Dimensionamiento de campaña y definición de incentivos", "owner": "Canales y Atención", "month": "" },
    { "title": "Elaboración de base de campaña", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Elaboración de piezas de campaña", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Evaluación de resultados", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío de comunicaciones (SMS, Mail Pers, Portal)", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Gestión call out reincorporación", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Recepción comunicaciones y canales", "owner": "Canales y Atención", "month": "Abril" },
    { "title": "Revisión Journey Campaña Reincorporación", "owner": "Canales y Atención", "month": "Abril" }
  ],
  "recupero": [
    { "title": "Activación de reportes BI", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Planificación de campaña call y definición speech y objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Definición de comunicaciones y canales", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Dimensionamiento de campaña y definición de incentivos", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Elaboración de base de campaña", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Evaluación de resultados", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Gestión call out recupero", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Revisión Journey Campaña Recupero", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Actualización de base de campaña", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Definición de acción: deuda de alumnos", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Solicitar a Admisión la lista de precios actuales por campus/carrera", "owner": "Canales y Atención", "month": "Mayo" },
    { "title": "Solicitar a PyGA (Eduardo) los planes de estudio para el periodo de Recupero Agosto 24", "owner": "Canales y Atención", "month": "Mayo" }
  ],
  "inasistencia": [
    { "title": "Activación de reportes BI", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Planificación de campaña call y definición speech y objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Definición de comunicaciones y canales", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Elaboración de base de campaña (semanal)", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Elaboración de piezas de campaña", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Evaluación de resultados", "owner": "Canales y Atención", "month": "Octubre" },
    { "title": "Gestión call out inasistencia", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Revisión de reglas de generación de base", "owner": "Canales y Atención", "month": "Julio" }
  ],
  "tricas-cuatricas": [
    { "title": "Activación de reportes BI", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Planificación de campaña call y definición speech y objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Elaboración de base de campaña (CGT, CGT bimodular, Pregrado)", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Elaboración de piezas de campaña", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Evaluación de resultados de comunicación", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Gestión call out tricas y cuatricas", "owner": "Canales y Atención", "month": "Septiembre" }
  ],
  "rol-examenes": [
    { "title": "Comunicación de Rol de exámenes CGT", "owner": "Canales y Atención", "month": "Octubre" },
    { "title": "Comunicación de Rol de exámenes PREG", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Planificación y definición de estrategia", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Comunicación a Alumnos con NS en EXFI o EXPA", "owner": "Canales y Atención", "month": "Diciembre" }
  ],
  "talleres-tutorias": [
    { "title": "Activación de reportes BI", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Capacitación Calidad", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Difundir pieza de Exámenes Rezagados", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Difundir pieza de Tips para tus exámenes", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Difusión t&t a alumnos con nota baja en Ex. Admisión", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío diario de inscritos a talleristas", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío semanal de comunicaciones con programación de la semana actual y la siguiente (SMS, Mail, App, Portal) - docentes, DGA, coordinadores", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío semanal de comunicaciones con programación de la semana actul y la siguiente (SMS, Mail, App, Portal)", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío semanal de material de repaso para cursos retadores", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Evaluación de resultados de comunicación", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Evaluación de resultados de desaprobación", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Evaluación de resultados de utilización", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Preparación de materiales", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Programación", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Revisión de lista de cursos retadores", "owner": "Canales y Atención", "month": "Diciembre" },
    { "title": "Planificación de sesiones y modelo de servicio", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Contratación de practicantes", "owner": "Canales y Atención", "month": "Junio" },
    { "title": "Revisión de sílabos", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Armar bibliografía por sesión para los cursos retadores con los links de los libros virtuales 2022", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Ajuste de dimensionamiento - Programación (Q matrícula)", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Ajuste de dimensionamiento - Programación (Utilización)", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Definicion cursos retadores (al cierre de notas de cada ciclo)", "owner": "Canales y Atención", "month": "Julio" },
    { "title": "Talleres saberes previos", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Carga material bibliografico", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Programacion TyT", "owner": "Canales y Atención", "month": "Agosto" }
  ],
  "cursos-flexibles": [
    { "title": "Planificación y definición de estrategia", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Comunicación de Evaluaciones Flexibles", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Comunicación de Cursos Flexibles", "owner": "Canales y Atención", "month": "Agosto" }
  ],
  "ivu": [
    { "title": "Actualización de las piezas de Encuesta IVU", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Validación de Cambios en la Preguntas del Encuesta IVU y segmentos", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Configuración de la Encuesta Encuesta IVU", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Validación de la correcta configuración de la Encuesta Encuesta IVU", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Envio semanal de comunicaciones de la Encuesta Encuesta IVU", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Planificación de campaña y definición de objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío de recordatorios de Inscripción - Tramo 1", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío de recordatorios de ingreso a conferencia - Tramo 1", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Envío de grabaciones de conferencia - Tramo 1", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Planificación de campaña y definición de objetivos y definición de estrategia de carga de base", "owner": "Canales y Atención", "month": "Agosto" },
    { "title": "Envío de recordatorios de Inscripción - Tramo 2", "owner": "Canales y Atención", "month": "Septiembre" },
    { "title": "Envío de recordatorios de ingreso a conferencia - Tramo 2", "owner": "Canales y Atención", "month": "Octubre" },
    { "title": "Envío de grabaciones de conferencia - Tramo 2", "owner": "Canales y Atención", "month": "Octubre" }
  ],
  "aulas-libres": [],
  "lab-mac": []
};
